import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Drink {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id; 

  //drinkType 
  final String drinkType;

  //When the drink occured
  DateTime dateTime;

  //Constructor
  Drink({this.id, required this.drinkType, required this.dateTime});
  
}//Drink
