import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
// The entity is the duration of the sleep session in ms (attenzione millisecondi!!!)
@entity
class SleepDuration {
  //Da tutor: id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  // duration of the sleep session
  final int durationValue;

  // when the sleep session occured
  final DateTime timestamp;

  // Default constructor
  SleepDuration(this.id, this.durationValue, this.timestamp);
}//SleepDuration