import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Goal {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  //goalName
  final String name;

  // money of the goal
  final double money;

  //When the goal is inserted
  DateTime dateTime;

  //Constructor
  Goal(
      {this.id,
      required this.name,
      required this.money,
      required this.dateTime});
} //Goal
