import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
// The entity is the duration of the sleep session in ms (attenzione millisecondi!!!)
@entity
class Sleep {
  //Da tutor: id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final DateTime dateOfSleep;

  final DateTime startTime;

  final DateTime endTime;

  final int duration;

  final int minutesToFallAsleep;

  final int minutesAsleep;

  final int minutesAwake;

  final int efficiency;

  final bool mainSleep;

  final String levelName;
  
  // final data;


  // Default constructor
  Sleep(this.id, this.dateOfSleep, this.startTime, this.endTime, this.duration, this.minutesToFallAsleep, this.minutesAsleep, this.minutesAwake, this.efficiency, this.mainSleep, this.levelName);
}//Sleep