import 'package:floor/floor.dart';
import 'package:intl/intl.dart';
import 'package:pim_group/models/entities/entities.dart';

//Here, we are saying to floor that this is a class that defines an entity
// The entity is the duration of the sleep session in ms (attenzione millisecondi!!!)
@entity
class Sleep {
  //Da tutor: id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final String dateOfSleep;
  final String startTime;
  final String endTime;
  final double duration;
  final int minutesToFallAsleep;
  final int minutesAsleep;
  final int minutesAwake;
  final int minutesAfterWakeup;
  final int efficiency;
  final String logType;
  final bool mainSleep;
  // final Map levels;
  // final Map data;

  // final DateTime dateOfSleep;

  // final DateTime startTime;

  // final DateTime endTime;

  // final int duration;

  // final int minutesToFallAsleep;

  // final int minutesAsleep;

  // final int minutesAwake;

  // final int efficiency;

  // final bool mainSleep;

  // final Levels level; //Non sono sicura sia giusto
  
  // final Data data; //Non sono sicura sia giusto

  //Perché sono due foreingkeys per la entity sleeps -ire

  // Default constructor
  Sleep(this.id, this.dateOfSleep, this.startTime, this.endTime,
    this.duration, this.minutesToFallAsleep, this.minutesAsleep,
    this.minutesAwake, this.minutesAfterWakeup,this.efficiency, 
    this.logType, this.mainSleep, );
    //this.levels, this.data

}//Sleep